<optgroup label="Dumb Bitch Lawyers Game">
    <option value="Phoenix Wright">Phoenix Wright</option>
    <option value="Mia Fey">Mia Fey</option>
    <option value="Miles Edgeworth">Miles Edgeworth</option>
    <option value="Maya Fey">Maya Fey</option>
    <option value="Pearl Fey">Pearl Fey</option>
    <option value="Dick Gumshoe">Dick Gumshoe</option>
    <option value="Franziska von Karma">Franziska von Karma</option>
    <option value="Ema Skye">Ema Skye</option>
    <option value="The Judge">The Judge</option>
    <option value="Apollo Justice">Apollo Justice</option>
    <option value="Trucy Wright">Trucy Wright</option>
    <option value="Athena Cykes">Athena Cykes</option>
    <option value="Frank Sahwit">Frank Sahwit</option>
    <option value="Misty Fey">Misty Fey</option>
    <option value="Morgan Fey">Morgan Fey</option>
    <option value="Winston Payne">Winston Payne</option>
    <option value="Larry Butz">Larry Butz</option>
    <option value="Manfred von Karma">Manfred von Karma</option>
    <option value="Wendy Oldbag">Wendy Oldbag</option>
    <option value="Diego Godot Armando">Diego Godot Armando</option>
    <option value="Dahlia Hawthorne">Dahlia Hawthorne</option>
    <option value="Klavier Gavin">Klavier Gavin</option>
    <option value="Simon Blackquill">Simon Blackquill</option>
    <option value="Bobby Fulbright">Bobby Fulbright</option>
    <option value="Nahyuta Sahdmadhi">Nahyuta Sahdmadhi</option>
    <option value="Rayfa Padma Khura'in">Rayfa Padma Khura'in</option>
    <option value="Will Powers">Will Powers</option>
    <option value="Lotta Hart">Lotta Hart</option>
    <option value="Maggey Byrde">Maggey Byrde</option>
    <option value="Shelly de Killer">Shelly de Killer</option>
    <option value="Adrian Andrews">Adrian Andrews</option>
    <option value="Marvin Grossberg">Marvin Grossberg</option>
    <option value="Gregory Edgeworth">Gregory Edgeworth</option>
    <option value="Director Hotti">Director Hotti</option>
    <option value="Kay Faraday">Kay Faraday</option>
    <option value="Shi-Long Lang">Shi-Long Lang</option>
    <option value="Tyrell Badd">Tyrell Badd</option>
    <option value="April May">April May</option>
    <option value="Redd White">Redd White</option>
    <option value="Dee Vasquez">Dee Vasquez</option>
    <option value="Yanni Yogi">Yanni Yogi</option>
    <option value="Damon Gant">Damon Gant</option>
    <option value="Lana Skye">Lana Skye</option>
    <option value="Jake Marshall">Jake Marshall</option>
    <option value="Angel Starr">Angel Starr</option>
    <option value="Ini Miney">Ini Miney</option>
    <option value="Acro">Acro</option>
    <option value="Matt Engarde">Matt Engarde</option>
    <option value="Luke Atmey">Luke Atmey</option>
    <option value="Furio Tigre">Furio Tigre</option>
    <option value="Kristoph Gavin">Kristoph Gavin</option>
    <option value="Alita Tiala">Alita Tiala</option>
    <option value="Daryan Crescend">Daryan Crescend</option>
    <option value="Vera Misham">Vera Misham</option>
    <option value="Magnifi Gramarye">Magnifi Gramarye</option>
    <option value="Thalassa Gramarye">Thalassa Gramarye</option>
    <option value="Zak Gramarye">Zak Gramarye</option>
    <option value="Valant Gramarye">Valant Gramarye</option>
    <option value="Spark Brushel">Spark Brushel</option>
    <option value="Gaspen Payne">Gaspen Payne</option>
    <option value="Juniper Woods">Juniper Woods</option>
    <option value="Aura Blackquill">Aura Blackquill</option>
    <option value="Ahlbi Ur'gaid">Ahlbi Ur'gaid</option>
    <option value="Inga Karkhuul Haw'kohd Dis'nahm Bi'ahni Lawga Ormo Pohmpus Da'nit Ar'edi Iz Khura'in III">Inga Karkhuul Haw'kohd Dis'nahm Bi'ahni Lawga Ormo Pohmpus Da'nit Ar'edi Iz Khura'in III</option>
    <option value="Dhurke Sahdmadhi">Dhurke Sahdmadhi</option>
    <option value="Datz Are'bal">Datz Are'bal</option>
    <option value="Ga'ran Sigatar Khura'in">Ga'ran Sigatar Khura'in</option>
    <option value="Jove Justice">Jove Justice</option>
    <option value="Amara Sigatar Khura'in">Amara Sigatar Khura'in</option>
    <option value="Calisto Yew">Calisto Yew</option>
    <option value="Quercus Alba">Quercus Alba</option>
    <option value=""Teikun Ō"">"Teikun Ō"</option>
    <option value="Tateyuki Shigaraki">Tateyuki Shigaraki</option>
    <option value="Ryōken Hōinbō">Ryōken Hōinbō</option>
    <option value="Hakari Mikagami">Hakari Mikagami</option>
    <option value="Yumihiko Ichiyanagi">Yumihiko Ichiyanagi</option>
    <option value="Bansai Ichiyanagi">Bansai Ichiyanagi</option>
    <option value="Sota Sarushiro">Sota Sarushiro</option>
</optgroup>
<optgroup label="Dumb Bitch Lawyers Game except Victorian era">
    <option value="Ryunosuke Naruhodo">Ryunosuke Naruhodo</option>
    <option value="Susato Mikotoba">Susato Mikotoba</option>
    <option value="Herlock Sholmes">Herlock Sholmes</option>
    <option value="Iris Wilson">Iris Wilson</option>
    <option value="Barok van Zieks">Barok van Zieks</option>
    <option value="Kazuma Asogi">Kazuma Asogi</option>
    <option value="Taketsuchi Auchi">Taketsuchi Auchi</option>
    <option value="Gina Lestrade">Gina Lestrade</option>
    <option value="Soseki Natsume">Soseki Natsume</option>
    <option value="Yujin Mikotoba">Yujin Mikotoba</option>
</optgroup>
<optgroup label="Angry Dog Boi Anime">
    <option value="Inuyasha">Inuyasha</option>
    <option value="Kagome Higurashi">Kagome Higurashi</option>
    <option value="Miroku">Miroku</option>
    <option value="Sango">Sango</option>
    <option value="Shippo">Shippo</option>
    <option value="Kirara">Kirara</option>
    <option value="Towa Higurashi">Towa Higurashi</option>
    <option value="Setsuna">Setsuna</option>
    <option value="Moroha">Moroha</option>
    <option value="Kikyo">Kikyo</option>
    <option value="Sesshomaru">Sesshomaru</option>
    <option value="Jaken">Jaken</option>
    <option value="Rin">Rin</option>
    <option value="A-Un">A-Un</option>
    <option value="Kohaku">Kohaku</option>
    <option value="Koga">Koga</option>
    <option value="Kaede">Kaede</option>
    <option value="Myoga">Myoga</option>
    <option value="Totosai">Totosai</option>
    <option value="Naraku">Naraku</option>
    <option value="Demon of the Shikon Jewel">Demon of the Shikon Jewel</option>
    <option value="Magatsuhi">Magatsuhi</option>
    <option value="Kanna">Kanna</option>
    <option value="Kagura">Kagura</option>
    <option value="Goshinki">Goshinki</option>
    <option value="Juromaru">Juromaru</option>
    <option value="Kageromaru">Kageromaru</option>
    <option value="Muso/Onigumo">Muso/Onigumo</option>
    <option value="Akago (the Infant)">Akago (the Infant)</option>
    <option value="Moryomaru">Moryomaru</option>
    <option value="Hakudoshi">Hakudoshi</option>
    <option value="Byakuya">Byakuya</option>
    <option value="Kyokotsu">Kyokotsu</option>
    <option value="Jakotsu">Jakotsu</option>
    <option value="Mukotsu">Mukotsu</option>
    <option value="Renkotsu">Renkotsu</option>
    <option value="Ginkotsu">Ginkotsu</option>
    <option value="Suikotsu">Suikotsu</option>
    <option value="Bankotsu">Bankotsu</option>
    <option value="Hachiemon (Hachi)">Hachiemon (Hachi)</option>
    <option value="Jinenji">Jinenji</option>
    <option value="Shiori">Shiori</option>
    <option value="Goryomaru">Goryomaru</option>
    <option value="The Dog General">The Dog General</option>
    <option value="Lady Izayoi">Lady Izayoi</option>
    <option value="Hosenki">Hosenki</option>
    <option value="Midoriko">Midoriko</option>
    <option value="Naohi">Naohi</option>
    <option value="Ginta">Ginta</option>
    <option value="Hakkaku">Hakkaku</option>
    <option value="Ayame">Ayame</option>
    <option value="Mushin">Mushin</option>
    <option value="Mrs. Higurashi">Mrs. Higurashi</option>
    <option value="Sota Higurashi">Sota Higurashi</option>
    <option value="Grandpa">Grandpa</option>
    <option value="Buyo">Buyo</option>
    <option value="Hojo">Hojo</option>
    <option value="Ayumi">Ayumi</option>
    <option value="Eri">Eri</option>
    <option value="Yuka">Yuka</option>
    <option value="Kin'u">Kin'u</option>
    <option value="Gyokuto">Gyokuto</option>
    <option value="Hisui">Hisui</option>
    <option value="Takechiyo">Takechiyo</option>
    <option value="Riku">Riku</option>
    <option value="Jyūbei">Jyūbei</option>
    <option value="Mei Higurashi">Mei Higurashi</option>
    <option value="Moe Higurashi">Moe Higurashi</option>
    <option value="Kirinmaru">Kirinmaru</option>
    <option value="Zero">Zero</option>
    <option value="Jakotsumaru">Jakotsumaru</option>
    <option value="Rion">Rion</option>
    <option value="Kyūki">Kyūki</option>
    <option value="Tōkotsu">Tōkotsu</option>
    <option value="Konton">Konton</option>
    <option value="Tōtetsu">Tōtetsu</option>
</optgroup>
<optgroup label="Angry Giant Nude Cannibal Genocidal Boi Anime">
    <option value="Eren Yeager">Eren Yeager</option>
    <option value="Mikasa Ackerman">Mikasa Ackerman</option>
    <option value="Armin Arlert">Armin Arlert</option>
    <option value="Reiner Braun">Reiner Braun</option>
    <option value="Darius Zackly">Darius Zackly</option>
    <option value="Keith Shadis">Keith Shadis</option>
    <option value="Jean Kirstein">Jean Kirstein</option>
    <option value="Marco Bott">Marco Bott</option>
    <option value="Sasha Blouse">Sasha Blouse</option>
    <option value="Krista Lenz">Krista Lenz</option>
    <option value="Ymir (ユミル, Yumiru)">Ymir (ユミル, Yumiru)</option>
    <option value="Floch Forster">Floch Forster</option>
    <option value="Erwin Smith">Erwin Smith</option>
    <option value="Hange Zoë">Hange Zoë</option>
    <option value="Moblit Berner">Moblit Berner</option>
    <option value="Nanaba">Nanaba</option>
    <option value="Louise">Louise</option>
    <option value="Holger">Holger</option>
    <option value="Levi Ackerman">Levi Ackerman</option>
    <option value="Eld Jinn">Eld Jinn</option>
    <option value="Oluo Bozado">Oluo Bozado</option>
    <option value="Petra Ral">Petra Ral</option>
    <option value="Hannes">Hannes</option>
    <option value="Rico Brzenska">Rico Brzenska</option>
    <option value="Nile Dok">Nile Dok</option>
    <option value="Hitch Dreyse">Hitch Dreyse</option>
    <option value="Boris Feulner">Boris Feulner</option>
    <option value="Captain Kenny Ackerman">Captain Kenny Ackerman</option>
    <option value="Djel Sanes">Djel Sanes</option>
    <option value="Fritz">Fritz</option>
    <option value="Rod Reiss">Rod Reiss</option>
    <option value="Frieda Reiss">Frieda Reiss</option>
    <option value="Aurille">Aurille</option>
    <option value="Deltoff">Deltoff</option>
    <option value="Gerald">Gerald</option>
    <option value="Roderich">Roderich</option>
    <option value="Grisha Yeager">Grisha Yeager</option>
    <option value="Carla Yeager">Carla Yeager</option>
    <option value="Kaya">Kaya</option>
    <option value="Ymir Fritz">Ymir Fritz</option>
    <option value="Karl Fritz">Karl Fritz</option>
    <option value="Founding Titan">Founding Titan</option>
    <option value="Attack Titan">Attack Titan</option>
    <option value="The Colossus Titan">The Colossus Titan</option>
    <option value="Armored Titan">Armored Titan</option>
    <option value="Female Titan">Female Titan</option>
    <option value="Beast Titan">Beast Titan</option>
    <option value="The Beast Titan">The Beast Titan</option>
    <option value="Jaw Titan">Jaw Titan</option>
    <option value="Cart Titan">Cart Titan</option>
    <option value="War Hammer Titan">War Hammer Titan</option>
    <option value="Sonny and Bean">Sonny and Bean</option>
    <option value="Calvi">Calvi</option>
    <option value="Zeke Yeager">Zeke Yeager</option>
    <option value="Bertolt Hoover">Bertolt Hoover</option>
    <option value="Annie Leonhart">Annie Leonhart</option>
    <option value="Marcel Galliard">Marcel Galliard</option>
    <option value="Porco Galliard">Porco Galliard</option>
    <option value="Pieck Finger">Pieck Finger</option>
    <option value="Gabi Braun">Gabi Braun</option>
    <option value="Falco Grice">Falco Grice</option>
    <option value="Colt Grice">Colt Grice</option>
    <option value="Willy Tybur">Willy Tybur</option>
    <option value="Lara Tybur">Lara Tybur</option>
    <option value="Mr. Yeager">Mr. Yeager</option>
    <option value="Mrs. Yeager">Mrs. Yeager</option>
    <option value="Faye Yeager">Faye Yeager</option>
    <option value="Tom Ksaver">Tom Ksaver</option>
    <option value="Gross">Gross</option>
    <option value="Koslow">Koslow</option>
    <option value="Niccolo">Niccolo</option>
    <option value="Eren Kruger">Eren Kruger</option>
    <option value="Dina">Dina</option>
    <option value="Grice">Grice</option>
    <option value="Yelena">Yelena</option>
    <option value="Onyankopon">Onyankopon</option>
    <option value="Kiyomi Azumabito">Kiyomi Azumabito</option>
</optgroup>
<optgroup label="Twin Himbo Demigod Bois babysitted by cool goth girl komik">
    <option value="Albert Morales">Albert Morales</option>
    <option value="Alexander Trese">Alexander Trese</option>
    <option value="Amang Aklat">Amang Aklat</option>
    <option value="Amang Paso">Amang Paso</option>
    <option value="Amang Paso">Amang Paso</option>
    <option value="Ammie">Ammie</option>
    <option value="Anneta">Anneta</option>
    <option value="Anton Trese">Anton Trese</option>
    <option value="Ariel">Ariel</option>
    <option value="Arko">Arko</option>
    <option value="Assu Ang">Assu Ang</option>
    <option value="Bagyon Kulimlim">Bagyon Kulimlim</option>
    <option value="Bagyon Lektro">Bagyon Lektro</option>
    <option value="Bagyon Yente">Bagyon Yente</option>
    <option value="Bantay">Bantay</option>
    <option value="Batman">Batman</option>
    <option value="Benjamin Chan">Benjamin Chan</option>
    <option value="Benjamin Lazaro">Benjamin Lazaro</option>
    <option value="Berto Labra">Berto Labra</option>
    <option value="Berto Labra">Berto Labra</option>
    <option value="Bianca Rivera">Bianca Rivera</option>
    <option value="Blaire Blasco">Blaire Blasco</option>
    <option value="Book Guardian">Book Guardian</option>
    <option value="Boyet">Boyet</option>
    <option value="Brim Yap Tan">Brim Yap Tan</option>
    <option value="Cal Duck">Cal Duck</option>
    <option value="Captain German">Captain German</option>
    <option value="Captain Guerrero">Captain Guerrero</option>
    <option value="Carlos Trese">Carlos Trese</option>
    <option value="Charlie Martinez">Charlie Martinez</option>
    <option value="Corporal Raul Lanares">Corporal Raul Lanares</option>
    <option value="Dante Blasco">Dante Blasco</option>
    <option value="Darago and Darranga">Darago and Darranga</option>
    <option value="Datu Gantes">Datu Gantes</option>
    <option value="Datu Karagatan">Datu Karagatan</option>
    <option value="Datu Rato">Datu Rato</option>
    <option value="Death Maidens">Death Maidens</option>
    <option value="Ding Vargas">Ding Vargas</option>
    <option value="Dober">Dober</option>
    <option value="Dolph and Ting">Dolph and Ting</option>
    <option value="Doma">Doma</option>
    <option value="Dr. Karl Burgos">Dr. Karl Burgos</option>
    <option value="Dr. Petra Gallaga">Dr. Petra Gallaga</option>
    <option value="Dr. Rianne Nicah">Dr. Rianne Nicah</option>
    <option value="Dyksona">Dyksona</option>
    <option value="Elizabeth Victoria">Elizabeth Victoria</option>
    <option value="Emilio">Emilio</option>
    <option value="Emissary">Emissary</option>
    <option value="Enteng Fernandez">Enteng Fernandez</option>
    <option value="Ernesto">Ernesto</option>
    <option value="Executioner's Squad">Executioner's Squad</option>
    <option value="Father Alloy">Father Alloy</option>
    <option value="Father Bronze">Father Bronze</option>
    <option value="Father Matt">Father Matt</option>
    <option value="Florabelle Campos">Florabelle Campos</option>
    <option value="Fortunato Alvares">Fortunato Alvares</option>
    <option value="General Ramon Lanares">General Ramon Lanares</option>
    <option value="General Wilson Hidalgo">General Wilson Hidalgo</option>
    <option value="Gina Santos">Gina Santos</option>
    <option value="Ginny Flores">Ginny Flores</option>
    <option value="Governor Sunny Romualdez">Governor Sunny Romualdez</option>
    <option value="Green-Eyed Sister">Green-Eyed Sister</option>
    <option value="Gregorio Revilla">Gregorio Revilla</option>
    <option value="Hank Sparrow">Hank Sparrow</option>
    <option value="Hannah">Hannah</option>
    <option value="Hannibal Caparas">Hannibal Caparas</option>
    <option value="Heather Evangelista">Heather Evangelista</option>
    <option value="Hector Mendoza">Hector Mendoza</option>
    <option value="Herbert Flores">Herbert Flores</option>
    <option value="Herbert Tomas">Herbert Tomas</option>
    <option value="House of Arko">House of Arko</option>
    <option value="Ian Solomon">Ian Solomon</option>
    <option value="Ibu">Ibu</option>
    <option value="Iglap">Iglap</option>
    <option value="Irago">Irago</option>
    <option value="Irma Allegra">Irma Allegra</option>
    <option value="Janette Lucero">Janette Lucero</option>
    <option value="Janjan Estrella">Janjan Estrella</option>
    <option value="Jay Gerson">Jay Gerson</option>
    <option value="Jeremy Gotianleung">Jeremy Gotianleung</option>
    <option value="Jimmy de la Strada">Jimmy de la Strada</option>
    <option value="Jimmy Trese">Jimmy Trese</option>
    <option value="Jobert">Jobert</option>
    <option value="Jonjon del Mundo">Jonjon del Mundo</option>
    <option value="Juan Tamad">Juan Tamad</option>
    <option value="Jzun Jzun and Big Beng">Jzun Jzun and Big Beng</option>
    <option value="Katya Sanchez">Katya Sanchez</option>
    <option value="Kenbhoy Calzada">Kenbhoy Calzada</option>
    <option value="Linda Blasco">Linda Blasco</option>
    <option value="Lorenzo Genio">Lorenzo Genio</option>
    <option value="Madame">Madame</option>
    <option value="Maliksi">Maliksi</option>
    <option value="Mama Grande">Mama Grande</option>
    <option value="Manang Muning">Manang Muning</option>
    <option value="Mang Art">Mang Art</option>
    <option value="Mang Recardo">Mang Recardo</option>
    <option value="Marco Guerrero">Marco Guerrero</option>
    <option value="Maria Makiling">Maria Makiling</option>
    <option value="Marianne de los Santos">Marianne de los Santos</option>
    <option value="Marvin Ignacio">Marvin Ignacio</option>
    <option value="Mary-Anne Alvarez">Mary-Anne Alvarez</option>
    <option value="Max">Max</option>
    <option value="Max Alva">Max Alva</option>
    <option value="Melchor Policarpio">Melchor Policarpio</option>
    <option value="Metalero">Metalero</option>
    <option value="Michael Andara">Michael Andara</option>
    <option value="Michael Martinez">Michael Martinez</option>
    <option value="Miranda Trese">Miranda Trese</option>
    <option value="Mr. Armanaz III">Mr. Armanaz III</option>
    <option value="Mr. Gotianleung">Mr. Gotianleung</option>
    <option value="Mr. Manzano">Mr. Manzano</option>
    <option value="Mr. Sorbetero">Mr. Sorbetero</option>
    <option value="Ms. De La Rosa">Ms. De La Rosa</option>
    <option value="Nida Vargas">Nida Vargas</option>
    <option value="Ninja Master">Ninja Master</option>
    <option value="Nino">Nino</option>
    <option value="Nova Aurora">Nova Aurora</option>
    <option value="Nuno Sa Manhole">Nuno Sa Manhole</option>
    <option value="Nuno the Snitch">Nuno the Snitch</option>
    <option value="Oriol the Enchantress">Oriol the Enchantress</option>
    <option value="Pamela">Pamela</option>
    <option value="Paquito Daza">Paquito Daza</option>
    <option value="Puti">Puti</option>
    <option value="Ra's al Ghul">Ra's al Ghul</option>
    <option value="Rakuda">Rakuda</option>
    <option value="Ramka">Ramka</option>
    <option value="Ramona">Ramona</option>
    <option value="Rat King">Rat King</option>
    <option value="Raul Lazaro">Raul Lazaro</option>
    <option value="Raymond Tomas">Raymond Tomas</option>
    <option value="Rey">Rey</option>
    <option value="Rick Trese">Rick Trese</option>
    <option value="Roberto Rodriguez">Roberto Rodriguez</option>
    <option value="Rose">Rose</option>
    <option value="Saglit">Saglit</option>
    <option value="Sancho Santamaria">Sancho Santamaria</option>
    <option value="Santelmo">Santelmo</option>
    <option value="Seepul">Seepul</option>
    <option value="Sergeant Scullion">Sergeant Scullion</option>
    <option value="Sergeant Tapia">Sergeant Tapia</option>
    <option value="Seven Seers">Seven Seers</option>
    <option value="Señor Armanaz">Señor Armanaz</option>
    <option value="Sidapa">Sidapa</option>
    <option value="Sinag">Sinag</option>
    <option value="Spunky Hontiveros">Spunky Hontiveros</option>
    <option value="Stephen">Stephen</option>
    <option value="Supling">Supling</option>
    <option value="Susan Bagyo">Susan Bagyo</option>
    <option value="Sytan">Sytan</option>
    <option value="T'Lang Khan">T'Lang Khan</option>
    <option value="Tai Leung Wong">Tai Leung Wong</option>
    <option value="Talagbusao">Talagbusao</option>
    <option value="Teresita Sala">Teresita Sala</option>
    <option value="Tereza">Tereza</option>
    <option value="The Astronomer">The Astronomer</option>
    <option value="The Hand">The Hand</option>
    <option value="The Judge">The Judge</option>
    <option value="The Kambal">The Kambal</option>
    <option value="Tomas Dominic Villaceran">Tomas Dominic Villaceran</option>
    <option value="Vanne">Vanne</option>
    <option value="Wari">Wari</option>
    <option value="William Blasco">William Blasco</option>
    <option value="Wolverine">Wolverine</option>
    <option value="Zabelle">Zabelle</option>
</optgroup>